### PR TITLE
Enhanced UI and fixed the footer overflow and added dynamic time

### PR DESCRIPTION
**Pull request by mangalgithub**
UI enhancement

https://github.com/adityarai0705/CodeTogether/assets/127006680/d4321233-c910-4d38-b5fe-9a284f1c9503

https://github.com/adityarai0705/CodeTogether/assets/127006680/0cf1d6d8-611e-4592-832d-8c2350b1494c

Footer

https://github.com/adityarai0705/CodeTogether/assets/127006680/a65b148c-67d4-4bb3-b0c9-ec69861fbde5

### CODE REVIEW

**Comment by mangalgithub** [comment]
Hi! @adityarai0705  I have enhanced the UI of buttons and fixed the overflow of footer and added the dynamic year in the footer section. Pls review the changes and merge it if everything sounds good to you else reach out to me for suggestions.
Thank you!

**Comment by adityarai0705** [comment]
The animations of the button were meant to be the way they are. Additional animations are not required. However your contribution in the footer is good. Remove the changes in the buttons and only keep your changes in the footer. Then I will merge your PR.

**Comment by mangalgithub** [comment]
Hey! @adityarai0705 I have made the changes suggested by you. Now review and merge it.

**Comment by adityarai0705** [comment]
Yepp! It's good now

**Pull request merged**
